version: "3.1"
services:
  pont-mongodb:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm start
    container_name: pont-mongodb
    ports:
      - "3332:3332"
    restart: always
    volumes:
      - .:/usr/src/pont-mongodb
